# Render Blueprint for EV Charge Network Frontend

services:
  - type: web
    name: evoltsoft-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s -l 10000 dist
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        fromSecret: VITE_API_URL
    build:
      nodeVersion: 18.x
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: '/*'
        destination: '/index.html'
    headers:
      - name: 'Content-Type'
        values: ['text/css; charset=utf-8']
      - name: 'X-Content-Type-Options'
        values: ['nosniff']
    buildCommand: |
      npm install
      npm run build
    buildOutputs:
      - dist
    autoDeploy: true
    plan: free
    region: oregon
    healthCheckPath: /
    
  - type: environment
    name: evoltsoft-frontend-env
    env:
      VITE_API_URL: "https://evoltsoft.onrender.com/api"
    secrets:
      - name: VITE_API_URL
        value: "https://evoltsoft.onrender.com/api"
