# Render Blueprint for EV Charge Network Frontend

services:
  - type: web
    name: evoltsoft-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        fromSecret: VITE_API_URL
    build:
      nodeVersion: 18.x
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: '/*'
        destination: '/index.html'
    autoDeploy: true
    plan: free
    region: oregon
    healthCheckPath: /
    
  - type: environment
    name: evoltsoft-frontend-env
    env:
      VITE_API_URL: "https://evoltsoft.onrender.com/api"
    secrets:
      - name: VITE_API_URL
        value: "https://evoltsoft.onrender.com/api"
